oddbird/popover-polyfill

index.html, src/popup.ts, tests/defaultopen.spec.ts
Following from #1 this adds support for `defaultOpen`, which should open the first marked popup on page load.
=> add support for defaultOpen

src/popup.css, src/popup.ts, tests/dismiss.spec.ts
This adds the `:open` pseudo-pseudo-class (that is, it looks like a psuedo class but it's a regular class with an escaped `:`) which allows us to query-select for all open popups. This allows us to close all auto/hint popups on click, by using a queryselector. It also allows us to move some of the required CSS into the stylesheet, rather than through inline syles in JS.
I've also added tests to affirm the click dismiss behaviour.
=> add click to dismiss behaviour

src/popup.ts
The current implementation uses a `Set` to track visible elements, but if these are _removed_ from the DOM before being hidden, then this will leak memory as it holds a hard reference. We can instead use a `WeakSet` which weakly holds references to the elements.
N/A
N/A
=> use weakset for visible elements

index.html, src/popover.ts, tests/triggers.spec.ts
`<button>` tags can have HTML inside of them. Currently the code for button handling checks to see if `event.target` is an appropriate button element, but this isn't accurate because the `event.target` will be the element that initiated the event, which could be the inner HTML of a button element.
In order to validate this, I've added some `<span>` elements inside the `<button>` tags, which fails the test suite as the buttons no longer function. In a separate commit I have corrected the event handler code to grab the closest applicable button element in the tree which has one of the `popoverXtarget` attributes.
If you checkout commit …
=> Fix event handling of buttons

README.md
As it's mentioned in the [CDN section](https://github.com/oddbird/popover-polyfill/blob/main/README.md?plain=1#L58) this part would be for prototyping or testing, so we could mention the CSS in here directly as well, even though that it's separated in the previous sections that are meant for production use and have some further description regarding CSS usage.
=> docs: even also include CSS within the CDN section

src/popover.css
The system colors are supported in every recent browser version: `canvastext` `canvas`
I don't know if we still need the fallbacks, or which browsers the polyfill supports. Otherwise we could do without the media-query.
=> use standard text and background colors

package-lock.json, package.json, src/index.ts, src/popover.ts, tests/basic.spec.ts, tests/events.spec.ts
This PR adds the `beforetoggle` event which is defined by the spec: https://whatpr.org/html/8221/popover.html#show-popover. It also exposes the global `BeforeToggleEvent` which is a new `Event` subclass that is exposed on `window`.
The `beforetoggle` event has two properties: `currentState` and `newState`. They are set to `'open'` or `'closed'` based on the current and desired state of the popover. The `beforetoggle` event when _showing_ a popover is cancelable. The event when hiding a popover is _not_ cancelable. This event does not bubble.
I've added tests for each of these conditions. Check out `events.spec.ts`
=> add beforetoggle events

CHANGELOG.md, README.md, index.html, src/data.ts, src/observer.ts, src/popover-helpers.ts, src/popover.ts, tests/triggers.spec.ts
Native popover in Chrome exposes "expanded" accessibility info for popover invokers, which allows assistive technologies to know that the button will expand some kind of dialog or menu.
This PR adds `aria-expanded=false` on all popover invoker buttons that target an `auto` popover, during page load or insertion into the DOM, and when a popover becomes visible, it will toggle `aria-expanded=true` for all invokers of a visible popover.
=> alter aria-expanded attributes for popover invokers

CHANGELOG.md, index.html, src/popover.ts
Consider the following HTML:
`<div popover=auto><a href="#" autofocus></a></div>`
When this popover is opened, the `<a>` that has `autofocus` should be focussed. This is currently behaviour present in this polyfill.
When this popover is _closed_ the focus should be restored to the last active element - only _if_ `popover=auto`. Thiis is specified in the steps here: https://html.spec.whatwg.org/multipage/popover.html#hide-popover-algorithm
Closes #7 
The tests are sufficient to reproduce this, but if you want to manually test:
- Focus on the button labelled `Click to show Popover 3`
- Use `Space` or `Enter` to enact the button
- Observe the link embedded in …
=> Add focus restoration support

CHANGELOG.md, src/data.ts, src/popover-helpers.ts, src/popover.ts, tests/dismiss.spec.ts
Working through various conditions, I discovered a bug in the existing behaviour. Calling `showPopover()` on an `auto` popover should hide all other `auto` popovers - there should only be one `auto` popover visible at a time.
I think this is related to #70 but I don't think #70 caused it.
This refactors a large part of the code to abstract the notion of hiding all auto popovers into a single function - and consequently the click handler gets heavily refactored. I've added a test to confirm that showing a auto popover hides others and done a fair amount of manual exploratory testing and I haven't seen this introduce any further regressions.
The tests should …
=> Showing an `auto` popover hides all other `auto` popovers

CHANGELOG.md, src/popover.ts, tests/dismiss.spec.ts
This PR adds support for the `Escape` key causing all auto popovers to be dismissed.
- Enact the `Click to show Popover 3` button
- Observe popover 3 is open
- Press Escape
- Observe popover 3 is now closed.
=> Add escape to dismiss

README.md, index.html, src/popover-helpers.ts, tests/triggers.spec.ts
In a misinterpretation of the spec in #86 a regression was introduced whereby the invoker can cause toggles to be no-ops. The reason is largely to do with the `nearestInclusiveTargetPopoverForInvoker` which was not written close to the spec, instead it was using `nearestInclusivePopover(target.popoverTarget)` which is not appropriate if the target contained nested elements like spans, or a composed event came through a shadow boundary.
This fixes that by rewriting these algos to use the spec methodology.
Tests should cover these scenarios.
Try clicking the `Click to toggle shadowed Popover (auto)` though, which should toggle, and you might find once it's …
=> rewrite nearestInclusive.* algos to be closer to the spec

CHANGELOG.md, README.md, src/popover-helpers.ts, src/popover.css, src/popover.ts, tests/basic.spec.ts
A potentially controversial change.
By default running something like `el.matches(':open')` on a browser without native Popover will result in an exception:
Chrome:
```
DOMException: Failed to execute 'matches' on 'Element': ':open' is not a valid selector.
```
Firefox:
```
DOMException: Element.matches: ':open' is not a valid selector
```
This means users of this polyfill need to work around this; either by using a `try`/`catch`, or by doing feature detection up front, e.g.:
```js
let openSelector = ':open'
try {
document.querySelector(openSelector)
} catch {
// use polyfilled selector instead
openSelector = '.\\:open'
}
```
This is a little cumbersome and has to be done for every selector you intend to use, and given we're patching prototype methods anyway, perhaps it could be useful …
=> Patch qsa matches closest to accept `:popover-open`

src/popover-helpers.ts, tests/edge-cases.spec.ts
Prior to this change, a popover removed from the document would still be in the autoPopovers set, and subsequently `topMostPopverAncestor` would return disconnected elements, causing `closeAllPopovers` to hit an infinite loop:
1. `hidePopover` is called
2. `closeAllPopovers` is called
3. `topMostPopoverAncestor` is called and returns disconnected element.
4. `hidePopover(topMost)` is called but returns false, as the element is disconnected.
5. `topMostPopoverAncestor` is called, but it returns the same element. Repeat step 4, infinite loop.
This commit alters `topMostAutoPopover` to check if the element is disconnected, and remove it from the set if so, only returning the first connected element.
1. `hidePopover` is called
2. `closeAllPopovers` is called
3. `topMostPopoverAncestor` is …
=> remove disconnected autoPopovers during topMostPopoverAncestor algo

src/popover.ts
To demonstrate this, you can see this in action if you go to the [demo](https://popover-polyfill.netlify.app/) in a browser that doesn't natively implement popover, and in the console execute:
```js
document.querySelector(null);
```
This causes some interop issues with other 3rd party libraries.
`document.querySelector` does not throw an error, and returns null.
Error thrown: Uncaught TypeError: can't access property "includes", selector is null
Firefox:
=> fix: querySelector APIs support null/undefined (closes #104)

index.html, src/popover-helpers.ts, src/popover.css, src/popover.ts
This PR changes the CSS and JS in some ways that support various combinations of esoteric browsers+flags. It fixes the following:
- Chrome 113 with Experimental Web Platform Features enabled. This browser supports native popover but with the `:open` psuedo selector (not `:popover-open`).
- Safari Technical Preview 166-171. These browsers support `popover` but either with `:open`, or both `:open` _and_ `:popover-open`.
- Older versions of Chromium such as 87, which includes alts like Qutebrowser, and older versions of Firefox such as Firefox 91, which includes alts like Seamonkey, Watefox Classic. These browsers don't support `@supports selector()`, `width: fit-content`, `inset`, nor do they support `node.getRootNode()`, `ShadowRoot`, or `HTMLDialogElement`. Luckily these are all fairly …
=> tweak styles & guard some code in older browsers

src/popover.ts
Some older browsers such as Chrome 98 have `adoptedStyleSheets` but it is a frozen array, rather than an `ObservableArray`, and can only be assigned to rather than `push()`ed to. Pushing to a frozen array causes an error to be thrown and so the polyfill doesn't work in those browsers if we continue to use push.
The fix for this is to always use an assignment on the array, it's a little slower the impact will be negligible.
See https://chromestatus.com/feature/5638996492288000 for some more detail.
- Visit https://popover-polyfill.netlify.app/ in Chrome <99 (I tested Chrome 96 for example).
- Note that the styles haven't loaded and popovers are all visible.
- Visit the console and note the error `TypeError: Cannot add property 0, object is not extensible`.
=> Assign adoptedStyleSheets rather than push

package-lock.json, package.json, src/index-fn.ts, src/index.ts, src/popover-helpers.ts
TypeScript recently added definitions for `popover` which conflict with the ones in this repository.
This updates the TS definitions to be compatible with those from TypeScript, so that users of older versions of TypeScript will still get the types, and for users of newer versions the code won't run into type conflicts.
```console
$ git checkout origin/main -f
$ npm i typescript@latest -D
$ npm run build # observe the errrors!
```
N/A
=> upgrade to typescript@5.2.2

src/popover-helpers.ts
=> Check slotted content for autofocus delegate

src/popover.ts
This wraps all selectors in a `:where()` (and also drops the redundant `:is()` which was there to lower specificity).
I tested this change on GitHub (where we use this polyfill) and I couldn't spot any regressions, styling worked as expected, and I spotted a couple of areas where we could lower our specificity. So I think this is is a worthwhile change.
This is effectively a no-op change, so no steps to reproduce.
This is effectively a no-op change, so no steps to reproduce.
=> use :where for selectors

src/popover.ts
This may go some of the way to fixing #147 which is still an issue for users, despite #153 which dropped selector specificity down to 0,0,0. Right now if a selector is used that has a specificity of 0,0,0, the polyfill will _still_ potentially override it as the popover styles get _appended_ to the head/adoptedStyleSheets, and as such will be lower in the cascade.
This change ensures that the popover stylesheet is _prepended_ rather than _appended_, which means it will appear as high up in the cascade as possible, rather than potentially at the bottom.
N/A
N/A
=> prepend popover stylesheet

README.md
Following discussion starting around https://github.com/oddbird/popover-polyfill/issues/147#issuecomment-1831642423, I've added an extra section to the caveats section explaining the issue and tracking back to it.
N/A
N/A
=> add :host caveats to caveats section

src/popover.ts
Browsers' native `popover` support allows for the `Esc` keypress to be preventable, which means that the popover won't close.
This is useful for capturing the `Esc` key behaviour from _within_ a popover to do other things without closing the popover.
Currently the polyfill does not allow for this. This PR checks the flag to ensure default hasn't been prevented.
I can follow up with steps/tests if we feel it necessary (time is short right now). 
=> allow esc to be defaultpreventable

src/popover.ts
This fixes https://github.com/oddbird/popover-polyfill/issues/139. Currently the demo page crashes in Firefox (without popovers enabled) if you click the "Click to toggle shadowed popover" button.
Looking through [a crash log](https://crash-stats.mozilla.org/report/index/7ac206de-9229-402a-9e6f-31ee80231019), we can see this is because Firefox tries to handle the popover using their popover logic, but the logic isn't guarded to check the feature flag, and it tries to get the element by its ID, which is empty. The empty id check fails for some reason, and we end up with a crash:
- Starting at Frame 6 we call [`mTarget->postHandleEvent(aVisitor);`](https://hg.mozilla.org/releases/mozilla-release/file/e26ce7fb8b2358ad45a84d34b1f5b6a1cc59d7fb/dom/events/EventDispatcher.cpp#l436)
- …
=> prevent default on clicks to avoid firefox crash

README.md
Hello! We recently had a 500ms render blocking script load, and I think it stems back to the docs for using this being a bit confusing on how to import the polyfill. I'm clarifying how to import the polyfill with almost all JS tooling. In fact, I can't think of any tooling that doesn't support this method.
=> Improve ESM Documentation

src/popover.ts
In https://github.com/philc/vimium/issues/4369 it has been noted that popovers don't work with the Firefox "Vimium" extension. This is, I suspect, because Vimium is synthesising click events and the popover polyfill checks if the event `isTrusted` (coming from the browser and not from scripts).
Trying to reproduce this in https://codepen.io/keithamus/pen/MWxJxOR we can see that the polyfill - when used - renders the button inert due to this guard, however native popover does not have the same guard and so in browsers with native popover (Chrome, WebKit) it is _not_ inert.
Consequently we should remove this guard to ensure behaviour aligns with native. 
https://github.com/philc/vimium/issues/4369
1. Open Firefox
2. Ensure `dom.element.popover.enabled` is set to `false`
3. Open …
=> Allow synthetic click events to target popovers

index.html, src/popover.ts, tests/triggers.spec.ts
#176 
- Populate the shadow dom of any element inside of a button that is a `popovertrigger`
- When a click originates from within the shadow dom, the popover is not triggers
=> Ensure click events correctly cross out of ShadowDOM

README.md, index.html, src/popover.ts, tests/edge-cases.spec.ts
User-agent and polyfilled styles should always have lowest priority, but if a consumer uses cascade layers (i.e. @layer) then polyfilled popover styles have highest priority and overwrite other styles unless they are also in a layer. This change puts polyfilled styles into a layer so that consumers can control layer order.
#175 (original issue and discussion)
Place a style that sets the background or color of any popover element into any `@layer` block. That style will only apply correctly after this change.
=> Add support for cascade layers

README.md
This adds a small change to the readme to provide people with workarounds on FOUC - where popovers may be temporarily visible while the JS loads.
=> add note about FOUC workarounds

README.md, src/index-fn.ts, src/popover.ts
This PR adds a `isPolyfilled` function to the public methods exposed by the polyfill.
The functions tests if the Popover API has been polyfilled, and it can be used to execute conditional code depending on if the Popover API is polyfilled or is native.
https://github.com/oddbird/popover-polyfill/issues/189
=> Add `isPolyfilled` method

src/popover.ts
Better support for SSR environments by internally checking for `typeof window === 'undefined'` before applying polyfill.
Addresses https://github.com/oddbird/popover-polyfill/issues/192#issuecomment-2033194487
=> Do not error if `window` is undefined

README.md
In #208, a user reported the polyfill was not able to be applied in certain builds of Chromium where part of the popover spec was enabled as part of the compilation (as opposed to a feature flag).
This caveat intentionally doesn't specify versions, as it is a function of the engine version, the engine compilation, and a user setting.
Closes #208
=> Add caveat about not polyfilling partial support

index.html, src/popover-helpers.ts, tests/dismiss.spec.ts
Adds support for slotting elements into a popover
#214
1. Go to https://codepen.io/Totati/pen/abgOBPP
2. Click on "Open popover" button.
3. Click on the red area. It's the slotted element.
Note: _I could not run playwright!_
=> Add support for slotting elements into popovers

CODEOWNERS, README.md, package.json
=> Add CJS build docs

src/popover.ts
Fixes #228 
Before:
```
document.body.popover = null;
document.body.popover; // "null"
```
Now:
```
document.body.popover = null;
document.body.popover; // null
```
=> Fix setting popover to null

README.md, css/base.css, css/demo.css, css/props.css, index.html, tests/edge-cases.spec.ts
Fixes #205 
-  On Sauce Labs, view the demo page in Safari 15 and 16 (Ventura OS) or versions of other browsers before they implemented cascade layers. 
- Compare the the deploy preview here to the live site. In the latest versions of browsers, everything should be the same (except for the updated `@layers` popover example). 
=> Clean up styles for older browsers

index.html, src/popover-helpers.ts, src/popover.ts, tests/basic.spec.ts, tests/hint.spec.ts
Fixes #227 
This adds support for `popover=hint`, but [as pointed out](https://github.com/oddbird/popover-polyfill/issues/227#issuecomment-2687441304), it would be great to selectively polyfill `hint` in browsers that don't support it but do have basic `popover` support. #242 tracks that specifically.
Relevant links:
- https://github.com/whatwg/html/pull/9778
- https://open-ui.org/components/popover-hint.research.explainer/#popoverhint-behavior
- https://developer.chrome.com/blog/popover-hint
- https://github.com/oddbird/popover-polyfill/pull/38
=> Support for popover=hint

src/index-fn.ts, src/index.ts, src/popover-helpers.ts, src/popover.ts, tests/methods.spec.ts
Returns showing state from `togglePopover`. 
This also documents the logic in cases where `force = false` and the popover is already hidden. 
Fixes #245 
Verify the 6 test cases in `test/methods.spec.ts` are as expected.
=> Return showing status from togglePopover

README.md, index.html, package.json
Closes #15 
The JS support could go back much further, but the current CSS is limited by `:where` and `:not` support. Manual testing seemed to reveal a bug in Firefox v84-87 with `height: -moz-fit-content`, so I limited it to FF88+.
=> Document browser support
